const bicepsExercises = 
[
  "Uginanie ramion z gumą",
  "Zginanie ramion ze sztangą nachwytem",
  "Uginanie ramion na TRX",
  "Uginanie ramion z hantlami nachwytem",
  "Uginanie ramion z hantlami w oparciu o ławeczkę",
  "Zginanie ramion z hantlami na modlitewniku chwytem młotkowym",
  "Uginanie ramienia z linką wyciągu dolnego stojąc",
  "Zginanie ramion z hantlami na modlitewniku",
  "Zottman curl",
  "Zginanie przedramienia z hantlem na modlitewniku",
  "Zginanie przedramion w wąskim chwycie ze sztangą stojąc",
  "Jednoczesne zginanie przedramion stojąc z wykorzystaniem wyciągów górnych",
  "Zginanie przedramion z drążkiem wyciągu dolnego na modlitewniku",
  "Zginanie przedramion z gryfem wyciągu górnego leżąc na ławce",
  "Zginanie przedramion z hantlami w chwycie młotkowym",
  "Zginanie przedramion w chwycie młotkowym siedząc na ławce",
  "Zginanie przedramion z gryfem łamanym na modlitewniku",
  "Zginanie przedramion na zewnątrz siedząc na ławce 75 stopni",
  "Zginanie przedramion z liną z wyciągu dolnego stojąc",
  "Zginanie przedramion ze sztangą łamaną stojąc",
  "Zginanie przedramion z hantlem w opadzie tułowia",
  "Zginanie przedramienia z hantlem – łokieć oparty na udzie",
  "Zginanie przedramion z hantlami z rotacją nadgarstka siedząc na ławce 90 stopni",
  "Zginanie przedramion z drążkiem wyciągu dolnego stojąc",
  "Zginanie przedramion ze sztangą stojąc",
];
const quadricepsExercises = 
[
  "Zakroki Zerchera",
  "Wyprosty kolan na maszynie jednonóż",
  "Syzyfki z asekuracją",
  "Przysiad ze sztangą ze stojaków",
  "Przysiad kolarski ze sztangą na plecach",
  "Przysiad kolarski z ciężarem przed klatką",
  "Przysiad kolarski",
  "Pistolet na podwyższeniu",
  "Odwrócone nordyckie opady z pomocą gumy",
  "Zakroki ze sztangą na plecach",
  "Wykroki długie chodzone z dłońmi trzymanymi na klatce piersiowej",
  "Wchodzenie na podwyższenie",
  "Przysiad wykroczny z nogą wykroczną na podwyższeniu z hantlami",
  "Przysiad sumo z kettlem/hantlą na stepach",
  "Wykroki w bok z TRX",
  "Przysiad z hantlami w pozycji front rack",
  "Przysiad wykroczny z hantlami",
  "Przysiad łyżwiarski",
  "Przysiad bułgarski z gumą",
  "Przysiad bułgarski (1 i 1/2)",
  "Zercher squat",
  "Wykroki skośne",
  "Spanish squat",
  "Przysiad do podwyższenia",
  "Goblet box squat",
  "Reverse drop lunges z hantlem",
  "Przysiad przedni z paskami",
  "Landmine squat",
  "Przysiad z gumą",
  "Pistolet na TRX",
  "Przysiad z wyskokiem na TRX",
  "Wykroki z ramionami w górze na TRX",
  "Zakroki na TRX",
  "Wypychanie suwnicy jednonóż",
  "Kozak squat z ciężarem",
  "Pistolet",
  "Przysiad sumo",
  "Przysiad z TRX",
  "Przysiad bułgarski z TRX",
  "Przysiad wykroczny z nogą zakroczną na podwyższeniu z hantlami",
  "Przysiad do skrzyni jednonóż",
  "Wchodzenie na podwyższenie z hantlami",
  "Zakroki z hantlami",
  "Wykroki chodzone z hantlami w dłoniach",
  "Side step up – wejście bokiem",
  "Przysiad z dłońmi trzymanymi za głową",
  "Wchodzenie na podwyższenie ze sztangą trzymaną na plecach",
  "Przysiad z kettlami",
  "Wykroki w miejscu ze sztangą trzymaną na plecach",
  "Przysiad z użyciem linek wyciągu dolnego",
  "Przysiad na maszynie Smitha",
  "Wykroki w miejscu z hantelkami",
  "Przysiad z hantelkami",
  "Wyprosty kolan na maszynie siedząc",
  "Wypychanie nogami na suwnicy",
  "Przysiad w wykroku na maszynie Smitha",
];
const hamstringAndGluteExercises = 
[
  "Żuraw z pomocą gumy",
  "Martwy ciąg jednonóż z półsztangą",
  "Landmine One leg RDL",
  "Unoszenie bioder z hantlą na jednej nodze w oparciu o ławeczkę",
  "Hip thrust with dumbbell",
  "Unoszenie nogi w klęku podpartym z gumą",
  "Banded donkey kick",
  "Unoszenie bioder w górę",
  "Glute bridge",
  "Unoszenie bioder na jednej nodze z hantlą",
  "Single leg dumbbell glute bridge",
  "Unoszenie bioder na jednej nodze w oparciu o ławeczkę",
  "Single leg hip thrust",
  "Pull through",
  "Hip cable adduction",
  "Hip adduction machine",
  "TRX hamstring curls (easy version)",
  "Cable kickback",
  "Kickback machine",
  "Kneeling hip abduction",
  "Cable sidekick",
  "Hip abduction machine",
  "Dumbbell frog hip thrust",
  "Miniband hamstring curls",
  "Hamstring curls machine – single leg",
  "Reverse hyper extension incline bench",
  "Side plank with hip abduction",
  "Reverse hyper extension",
  "Reverse hyper extension on bench",
  "Elevated stiff leg deadlift",
  "RDL kickstand with dumbbell",
  "RDL kickstand",
  "Pull through with band",
  "Clamshell exercise",
  "Assisted one leg RDL",
  "Hamstring walkout",
  "Good morning barbell",
  "Glute bridge (toes up)",
  "Copenhagen adduction",
  "Sumo elevated deadlift",
  "Kettlebell elevated deadlift",
  "Glute bridge with dumbbell",
  "Hip drop",
  "Elevated deadlift",
  "Banded good morning",
  "Landmine RDL",
  "Landmine deadlift",
  "Banded leg curl",
  "Banded single leg RDL",
  "Banded RDL",
  "Banded deadlift",
  "Banded glute bridge",
  "X walk",
  "Stiff leg deadlift",
  "Single leg hyperextension",
  "Ball leg curl (easy version)",
  "Glute ham raise (easy version)",
  "Hip thrust with dumbbell",
  "Frog hip thrust",
  "TRX hamstring curls",
  "Hamstring curls with dumbbell",
  "Single leg glute bridge",
  "Single leg dumbbell RDL",
  "Sumo deadlift",
  "Barbell glute bridge",
  "Barbell hip thrust",
  "Nordic curl",
  "Ball glute ham raise",
  "Dumbbell RDL",
  "Romanian deadlift",
  "Hamstring curls machine",
  "Ball leg curl",
];
const chestExercises = 
[
  "Wyciskanie stojąc z wykorzystaniem wyciągu lub bramy",
  "Cable chest press",
  "Wyciskanie hantli wąskim chwytem neutralnym na ławeczce płaskiej",
  "Dumbbell bench press - neutral grip",
  "Rozpiętki z gumą za plecami",
  "Banded chest fly",
  "Wyciskanie sztangi na ławce poziomej ze stojaków",
  "Pin bench press",
  "Wyciskanie z gumą za plecami",
  "Banded chest press",
  "Wyciskanie sztangi na podłodze w domu",
  "Barbell floor press – without rack",
  "Wyciskanie sztangi na podłodze",
  "Barbell floor press",
  "Wyciskanie na podłodze jednorącz",
  "One arm floor press",
  "Rozpiętki z hantlami w leżeniu na podłodze",
  "Floor chest fly",
  "Rozpiętki na TRX",
  "TRX chest fly",
  "Pompki podwieszane na TRX",
  "TRX suspended push ups",
  "Wyciskanie sztangi na ławce skośnej głową w dół",
  "Decline barbell bench press",
  "Pompki na TRX",
  "TRX push ups",
  "Dumbbell floor press",
  "Rozpiętki z wykorzystaniem wyciągu dolnego",
  "Low cable chest fly",
  "Przenoszenie sztangielki za głowę",
  "Dumbbell pullover",
  "Wyciskanie na suwnicy Smitha leżąc na ławce skośnej głową w dół",
  "Decline Smith machine press",
  "Wyciskanie sztangielek na ławce skośnej głową w dół",
  "Decline dumbbells bench press",
  "Pompki (wersja klasyczna)",
  "Push ups",
  "Rozpiętki z hantlami na ławce płaskiej",
  "Dumbbells chest fly",
  "Rozpiętki z wykorzystaniem wyciągów",
  "Cable chest fly",
  "Rozpiętki na maszynie butterfly",
  "Pec dec fly",
  "Pompki na poręczach",
  "Dips – chest version",
  "Wyciskanie sztangi na ławce płaskiej do brody, gilotyna",
  "Guillotine press",
  "Rozpiętki z wykorzystaniem wyciągu na ławce dodatniej",
  "Incline bench cable chest fly",
  "Wyciskanie na suwnicy Smitha leżąc na ławce płaskiej",
  "Smith bench press",
  "Rozpiętki z wykorzystaniem wyciągu na ławce płaskiej",
  "Bench cable chest fly",
  "Wyciskanie sztangielek na ławce dodatniej",
  "Incline dumbbell bench press",
  "Wyciskanie sztangielek chwytem neutralnym na ławce ze skosem dodatnim",
  "Incline dumbbell bench press neutral grip",
  "Rozpiętki z hantlami na ławce dodatniej",
  "Incline bench dumbbells chest fly",
  "Wznosy ramion z wykorzystaniem dolnego wyciągu",
  "Low cable arm raise – chest version",
  "Wyciskanie na maszynie hammer",
  "Hammer chest press",
  "Wyciskanie sztangi na ławce płaskiej",
  "Barbell bench press",
  "Wyciskanie sztangi na ławce dodatniej",
  "Incline barbell bench press",
  "Wyciskanie sztangielek na ławce płaskiej",
];
const backExercises = 
[
  "Wiosłowanie gumą w opadzie tułowia - Bent over banded row",
  "Ściąganie gumy jednorącz z nad głowy - One arm overhead banded lat pull down",
  "Ściąganie chwytu wyciągu górnego po skosie - Half kneeling one arm lat pulldown",
  "Ściąganie chwytu wyciągu górnego jednorącz - One arm lat pulldown",
  "Podciąganie podchwytem z martwego punktu - Chin ups - dead stop",
  "Podciąganie nachwytem z martwego punktu - Pull ups - dead stop",
  "Podciąganie chwytem neutralnym na pojedynczym drążku - Cliffhanger pull ups",
  "Podciąganie australijskie jednorącz - One arm australian pull ups",
  "Podciąganie australijskie podchwytem - Australian pull ups underhand grip",
  "Y raise z hantlami w opadzie tułowia - Bent over Y raise",
  "Wiosłowanie kettlebell z podłogi - Gorilla row kettlebell",
  "Wiosłowanie hantlami z podłogi - Gorilla row dumbbell",
  "Wiosłowanie w podporze na kolanach - Row renegade on knee",
  "Wiosłowanie w podporze z gumą miniband - Row renegade miniband",
  "Wiosłowanie w klęku jednonóż z gumą miniband - Half kneeling miniband row",
  "TRX Y raise - TRX Y raise",
  "TRX wiosłowanie jednorącz z rotacją - TRX one arm row",
  "Szrugsy ze sztangą - Barbell shrugs",
  "Wiosłowanie na TRX - TRX row",
  "Szrugsy z linkami wyciągu dolnego - Cable shrugs",
  "Szrugsy z hantlami - Dumbbell shrugs",
  "Seal row",
  "Podciąganie z pomocą nóg - Legs assisted pull ups",
  "Opuszczanie na drążku – podchwyt - Eccentric chin up",
  "Opuszczanie na drążku – nachwyt - Eccentric pull up",
  "Back widow",
  "Wiosłowanie półsztangą - One arm landmine row",
  "Zwis aktywny - Active hang",
  "Scap pull up",
  "Kayak row",
  "Prostopadłe ściąganie gumy do bioder leżąc - Band pullover – lying down position",
  "Prostopadłe ściąganie gumy do bioder stojąc - Band pullover",
  "Ściąganie gumy do klatki piersiowej - Band lat pulldown",
  "Ściąganie gumy za kark - Band lat pulldown behind the neck",
  "Wiosłowanie gumą - Band row",
  "Ściąganie chwytem neutralnym z wyciągu górnego - Lat pulldown – neutral grip",
  "Ściąganie drążka nachwytem na szerokość barków - Lat pulldown",
  "Wiosłowanie w oparciu o kolano - Dumbbell row – elbow on knee",
  "Wiosłowanie hantlą w oparciu ręką o ławeczkę - Dumbbell row – hand supported on bench",
  "Podciąganie chwytem młotkowym - Pull ups – neutral grip",
  "Podciąganie nachwytem z pomocą gumy oporowej - Banded pull ups",
  "Wiosłowanie sztangą nachwytem w pełnym opadzie tułowia - Bent over barbell row",
  "Wiosło Pendlaya - Pendlay row",
  "Trap Y raise",
  "Wiosłowanie w podporze – row renegade",
  "Wiosłowanie hantlą w klęku podpartym na ławeczce - Dumbbell row – knee supported",
  "Wiosłowanie hantlami w oparciu o ławkę skośną - Dumbbells row – chest supported",
  "Wiosłowanie sztangą trzymaną nachwytem do klatki w opadzie tułowia - Bent over barbell row",
  "Klasyczny martwy ciąg - Deadlift",
  "Wiosłowanie z wykorzystaniem kółek gimnastycznych, TRX lub sztangi - Inverted row",
  "Podciąganie na drążku trzymanym nachwytem - Pull ups",
  "Podciąganie na drążku trzymanym podchwytem - Chin ups",
  "Podciąganie na drążku trzymanym szeroko do karku - Behind the head pull ups",
  "Przyciąganie drążka wyciągu górnego do klatki podchwytem wąsko - Lat pulldown close grip",
  "Prostopadłe przyciąganie drążka wyciągu górnego do bioder - Cable pullover",
  "Wiosłowanie końcem sztangi chwytem neutralnym w opadzie tułowia - Landmine row neutral grip",
  "Przyciąganie końca sztangi jednorącz w opadzie tułowia - Single arm landmine row",
  "Przyciąganie linki wyciągu dolnego jednorącz - Single arm cable row",
  "Przyciąganie linki wyciągu dolnego siedząc - Cable row",
  "Ściąganie drążka wyciągu górnego do klatki nachwytem szeroko - Lat pulldown wide grip",
  "Ściąganie drążka wyciągu górnego trzymanego nachwytem za kark - Lat pulldown behind the head",
  "Unoszenie tułowia na ławce rzymskiej - Hyperextension",
  "Wiosłowanie hantlami w opadzie tułowia - Bent over dumbbells row",
  "Wiosłowanie na suwnicy Smitha w opadzie tułowia - Bent over row – Smith machine",
  "Wiosłowanie sztangą trzymaną podchwytem w opadzie tułowia",
];
const shoulderExercises = 
[
  "TRX odwrócone rozpiętki - TRX reverse fly",
  "TRX face pull",
  "Przenoszenie ramion z gumą miniband",
  "Shoulder mini band press",
  "Powell raise",
  "T raise z hantlami w opadzie tułowia",
  "Bent over T raise",
  "Rotacja wewnętrzna na wyciągu - Cable internal rotation",
  "Rotacja zewnętrzna na wyciągu - Cable external rotation",
  "Z-press",
  "Face pull z gumą",
  "Banded face pull",
  "Landmine press",
  "Landmine press half kneeling",
  "Wyciskanie jednorącz nad głowę z gumą",
  "Wyciskanie ramion z gumą nad głowę - Banded shoulder press",
  "Wznosy ramion w bok z gumą - Banded lateral raise",
  "Wznosy ramion w przód z gumą - Banded front raise",
  "Unoszenie ramion z hantlami w przód z przenoszeniem na boki - Front to side raises",
  "Cuban press",
  "Wyciskanie hantli w klęku jednonóż - Half kneeling single arm press",
  "Unoszenie ramienia z wykorzystaniem linki wyciągu dolnego - One arm cable lateral raise",
  "Rotacja zewnętrzna w leżeniu bokiem - External rotation – lying down position",
  "Rotacje kubańskie z hantlami - Cuban rotation",
  "Rotacje zewnętrzne ramienia hantlą siedząc - Dumbbell external rotation",
  "Przyciąganie liny z wyciągu do twarzy (Face pull)",
  "T raise na ławeczce",
  "Wyciskanie sztangi zza głowy stojąc - Behind the neck overhead press",
  "Wyciskanie sztangi nad głowę siedząc - Seated overhead press",
  "Wyciskanie sztangi na maszynie Smitha siedząc - Smith machine shoulder press",
  "Unoszenie ramion w przód ze sztangą w oparciu o ławkę dodatnią - Incline barbell front raise",
  "Arnoldki – wyciskanie hantli nad głowę z rotacją - Arnold press",
  "Odwodzenie linek w tył wyciągu stojąc - Cable rear delt fly",
  "Naprzemianstronne unoszenie ramion w przód z wykorzystaniem wyciągu dolnego - Alternating cable front raise",
  "Naprzemianstronne unoszenie ramion w przód ze sztangielkami - Alternating dumbbell front raise",
  "Naprzemienne wyciskanie hantli nad głowę stojąc - Alternating dumbbell shoulder press",
  "Podciąganie sztangi pod brodę - Upright barbell row",
  "Przyciąganie liny z wyciągu górnego do klatki piersiowej - Cable row to chest",
  "Wyciskanie ramion nad głowę siedząc z wykorzystaniem wyciągu - Seated cable shoulder press",
  "Unoszenie ramion w bok ze sztangielkami w pozycji siedzącej - Seated lateral raise",
  "Odwodzenie ramion w bok ze sztangielkami - Lateral raise",
  "Unoszenie ramion w przód ze sztangielkami - Front raise",
  "Unoszenie ramion w przód ze sztangielką trzymaną oburącz - One dumbbell front raise",
  "Wyciskanie sztangi nad głowę - Military press",
  "Wyciskanie hantli nad głowę siedząc - Seated overhead dumbbell press",
  "Wyciskanie hantli nad głowę stojąc - Overhead dumbbell press",
  "Wyciskanie nad głowę na maszynie chwytem neutralnym - Overhead machine press – neutral grip",
  "Wyciskanie nad głowę z linkami wyciągu dolnego - Overhead cable press",
  "Wyciskanie sztangielki jednorącz nad głowę stojąc - Single arm shoulder press",
  "Wznosy ramion w bok w opadzie tułowia siedząc - Seated bent-over raise",
  "Wznosy ramion w bok w opadzie tułowia - Bent-over raise",
];
const abExercises = 
[
  "TRX superman na kolanach - TRX superman on knees",
  "TRX body saw",
  "Rotacje w pozycji podporu bokiem - Rotating high side plank",
  "Rotacje w pozycji deski bokiem - Rotating side plank",
  "Pallof press w pozycji wykrocznej na wyciągu - Split stance cable pallof press",
  "Pallof press w pozycji wykrocznej - Split stance pallof press",
  "Dotykanie przeciwnych barków w podporze - Plank shoulder tap",
  "Deska na kolanach - Knee plank",
  "Deska bokiem na kolanach - Side plank on knee",
  "Chaos pallof press",
  "Przyciąganie ręki do przeciwnej nogi - Alternating toe touch",
  "Nożyce nogami - Scissors",
  "Deska na TRX - TRX plank",
  "Deska na piłce - Swiss ball plank",
  "Brzuszki z rękami na klatce piersiowej - Ab crunch",
  "Wycieraczki – nogi ugięte - Windshield wipers bent knees",
  "Wycieraczki – nogi proste - Windshield wipers",
  "Unoszenie prostych nóg na stojaku - Capitan's chair leg raise",
  "Unoszenie kolan na skos w zwisie na drążku - Hanging side knee raise",
  "Spięcia brzucha z linkami wyciągu górnego - Cable crunch",
  "Rotacje w klęku jednonóż z hantlą - Half kneeling dumbbell chop",
  "Przyciąganie kolan do klatki na stojaku - Capitan's chair knees raise",
  "Naprzemienne przyciąganie kolan z gumą miniband - Alternating knee to chest with miniband",
  "Krążenia ramion w podporze na piłce - Stir the pot",
  "Spacer farmera - Farmer walk",
  "Spacer farmera z ciężarem po jednej stronie nad klatką piersiową - Farmer walk front rack single arm weighted",
  "Spacer farmera z ciężarem nad klatką piersiową - Farmer walk front rack weighted",
  "Suitcase walk",
  "Pallof press na wyciągu - Cable pallof press",
  "Landmine twist",
  "Janda sit up",
  "Body saw",
  "Ab roller na kolanach z przedramionami na piłce - Ball rollout",
  "Unoszenie prostych nóg do drążka - Hanging leg raise",
  "Mountain climbers na TRX - TRX mountain climbers",
  "Pike TRX",
  "Superman na TRX - TRX Superman",
  "Deska bokiem na TRX - TRX side plank",
  "Rewersy - Reverse crunch",
  "Scyzoryk - Jackknife sit up",
  "Dead bug – nogi proste - Dead bug – straight legs",
  "Dead bug – nogi ugięte - Dead bug – bent legs",
  "Hollow body",
  "Semi hollow body",
  "Przyciąganie kolan pod klatkę na piłce - Ball knee to chest",
  "Przyciąganie kolan pod klatkę na TRX - TRX knee tuck",
  "Ab roller na kolanach - Ab roller on knee",
  "Ab roller na kolanach z piłką - Ball rollout",
  "Rotacje z gumą - Banded rotation",
  "Pallof press - Banded pallof press",
  "Rotacja boczna na wyciągu - Cable rotation",
  "Rotacje boczne po skosie – woodchoper - Cable woodchop",
  "Izometryczny skurcz mięśni brzucha w podporze przodem. Deska/ścianka/plank - Plank",
  "Naprzemienne przyciąganie łokci do kolan leżąc na plecach - Alternating elbow to knee crunch",
  "Naprzemienne sięganie do kostek leżąc - Alternating heel touches",
  "Przyciąganie kolan do klatki w zwisie na drążku - Hanging knee raise",
  "Rowerek - Bicycle crunch",
  "Spięcia brzucha leżąc na macie ze złączonymi stopami - Frog crunch",
  "Spięcia brzucha z nogami opartymi na piłce gimnastycznej - Ab crunch – leg on ball",
  "Świeca z prostowaniem nóg leżąc - Candlestick exercise",
  "Zginanie tułowia na maszynie siedząc. Spięcia brzucha na maszynie - AB crunch machine",
  "Unoszenie tułowia z podłoża. Spięcia brzucha leżąc - AB crunch",
];
const tricepsExercises = 
[
  "Prostowanie ramienia jednorącz w klęku podpartym na ławce płaskiej",
  "Prostowanie ramion z gumą pod stopami",
  "Prostowanie ramion w oparciu o ławeczkę",
  "Wyciskanie francuskie w leżeniu na podłodze",
  "Pompki w podporze tyłem z ugiętymi nogami",
  "Pompki w podporze tyłem z nogami na podwyższeniu",
  "Pompki na poręczach – samo opuszczanie",
  "Triceps rollback extension",
  "Prostowanie ramion na TRX",
  "Prostowanie ramion z linką wyciągu dolnego w opadzie tułowia",
  "Prostowanie ramion z linkami wyciągu górnego",
  "Wyciskanie francuskie z przenoszeniem ramion za głowę",
  "Wyciskanie sztangi wąskim chwytem",
  "Wyciskanie francuskie hantlami z przenoszeniem ramion za głowę",
  "Wyciskanie francuskie hantlami",
  "Wąskie pompki",
  "Pompki na poręczach z gumą",
  "Prostowanie ramion z hantlami za siebie w opadzie tułowia",
  "Prostowanie ramion leżąc na ławce z użyciem wyciągu górnego",
  "Pompki w podporze tyłem na ławeczce",
  "Pompki na triceps na poręczach",
  "Pompki w oparciu o sztangę wąskim chwytem",
  "Prostowanie przedramienia w pionie ze sztangielką",
  "Prostowanie przedramion w pionie ze sztangą trzymaną oburącz",
  "Prostowanie przedramion w pionie ze sztangielką trzymaną oburącz",
  "Prostowanie przedramion z gryfem łamanym trzymanym nachwytem z wyciągu górnego",
  "Prostowanie przedramion z gryfem prostym trzymanym nachwytem z wyciągu górnego",
  "Prostowanie przedramion z liną z wyciągu dolnego stojąc",
  "Prostowanie przedramion ze sztangą łamaną leżąc na ławce płaskiej",
  "Prostowanie przedramion ze sztangielką trzymaną oburącz siedząc",
  "Prostowanie ramienia jednorącz z wyciągu dolnego stojąc",
  "Prostowanie ramienia z wykorzystaniem wyciągu górnego",
  "Prostowanie ramion na maszynie triceps",
  "Prostowanie ramion z gryfem trzymanym podchwytem z wyciągu górnego",
  "Wąskie pompki na triceps. Diamentowe pompki",
  "Wyciskanie sztangi łamanej wąskim chwytem na ławeczce płaskiej",
  "Wyciskanie sztangi na suwnicy Smitha wąskim chwytem na triceps",
];
const calfExercises = 
[
  "Wspięcia na palce jednonóż",
  "Wspięcia na palce jednonóż z hantlami",
  "Wspięcia na palcach w pozycji siedzącej ze sztangą ułożoną na kolanach",
  "Wspięcia na palcach na suwnicy",
  "Wspięcia na palcach siedząc z użyciem sztangielki",
  "Wspięcia na palcach stojąc z hantlą",
  "Wspięcia na palcach stojąc z wykorzystaniem suwnicy Smitha",
  "Wspięcia na palcach stojąc ze sztangą trzymaną na plecach",
  "Wspięcia na palcach siedząc na maszynie",
];

// struktura przechowujaca wszystkie cwiczenia w grupach aby latwiej bylo sie do nich odwolywac
const exercises = 
[
  { name: "biceps", exercises: bicepsExercises },
  { name: "quadriceps", exercises: quadricepsExercises },
  { name: "hamstring_glutes", exercises: hamstringAndGluteExercises },
  { name: "chest", exercises: chestExercises },
  { name: "back", exercises: backExercises },
  { name: "shoulders", exercises: shoulderExercises },
  { name: "abs", exercises: abExercises },
  { name: "triceps", exercises: tricepsExercises },
  { name: "calves", exercises: calfExercises },
];
